### ISSUE TITLE
Logos and Icons

### ISSUE THREAD

**Issue by tgrey2024** [Carlos-n21/js-group#14]
**User Story:**
**As a** site user,
**I want to** see a logo and favicon in the site,
**so that I can** recognise the site and navigate it easily.

**Acceptance Criteria:**
- [ ] Use the correct sizes and file formats

**Tasks:**
- [x] Generate logo options on logo.ai
- [x] Agree on logo design, font and colours
- [x] Check logo has good contrast against browser background colour and any header/nav bar colour
- [x] Generate logo in different sizes and favicon (use [Favicon.io](https://favicon.io/))
