### ISSUE TITLE
New item

### ISSUE THREAD

**Issue by Carlos-n21** [Carlos-n21/js-group#2]
Story: I like to go shopping and find it hard to have a paper list with me, would like to have an app or site on my mobile that I can use to  to add a new to-do item to the list, and see all the things I want to buy.

**Acceptance criteria:**

- [ ] Showing different items that the user has added to the list
- [ ] Allow the user to add more items to the list

**Tasks:**

- [ ] Create an input text to write new items
- [ ] Create a button to add items to the list
