### ISSUE TITLE
Delete to-do item

### ISSUE THREAD

**Issue by tgrey2024** [Carlos-n21/js-group#4]
Story: I would like to be able to remove an item from my list if I realize I still have this item at home.

**Acceptance criteria:**

- [ ] Being able to remove item from the list created initially
- [ ] List being updated automatically as user removes item from list
- [ ] Item can be removed from Unordered list without reordering other list items 

**Tasks:**

- [ ] Ability to remove item from list
