### ISSUE TITLE
Clear input field

### ISSUE THREAD

**Issue by tgrey2024** [Carlos-n21/js-group#5]
User story: As a user, I want to clear the text I enter into the input field, so that I can clear the text quickly.

**Acceptance criteria:**

- [ ] Ability to clear text in text input box

**Tasks:**

- [ ] function to clear textbox
- [ ] add Clear button to call function
